version: "3"
services:

  shallot:
    image: markw/shallot:0.0.2
    hostname: "shallot"
    restart: always
    volumes:
    - ./shared-queries/:/home/grlc/queries/
    - ./config.ini:/home/grlc/grlc/config.default.ini
    ports:
     - "8088:80" 
    networks:
      - default
    environment:
      - DEBUG=true
      - GRLC_SPARQL_ENDPOINT=http://graphdb:7200/repositories/ACME-cde
      - GRLC_SERVER_NAME=localhost:8088
# this will be your server URL, if you want to serve from the outside.

networks:
  default:
    name: ACME_graphdb
    external: true
