version: "3"
services:

  grlc:
    image: markw/grlc_3.9.13:0.0.5
    hostname: "grlc"
    container_name: "grlc"
    restart: always
    volumes:
    - ./grlc-queries/:/home/grlc/queries/
    - ./config.ini:/home/grlc/grlc/config.default.ini
    ports:
     - "8088:80" 
    networks:
      - default
    environment:
      - DEBUG=true
      - GRLC_SPARQL_ENDPOINT=http://graphdb:7200/repositories/cde
      - GRLC_SERVER_NAME=localhost:8088
# this will be your server URL, if you want to serve from the outside.

networks:
  default:
    name: dpp_graphdb
    external: true
