version: "3"
services:

  # hitch:
  #   image: markw/hitch-f-i-a-b:0.0.1
  #   hostname: "hitch"
  #   restart: always
  #   volumes:
  #   - $PWD/proxy.conf:/etc/hitch/hitch.conf
  #   - $PWD/combined.pem:/etc/hitch/cert.pem  # this is YOUR cert + key pem file
  #   ports:
  #    - {FDP_PORT}:8443 # the left is what is exposed to the web.  The right must match the "frontend" port in proxy.comf
  #   networks:
  #     - {PREFIX}-default

  # FAIR Data Point client	
  fdp_client:
    image: fairdata/fairdatapoint-client:1.16.3
    hostname: fdpclient
    restart: always
    environment:
      FDP_HOST: fdp
    volumes:
      - ./fdp/variables.scss:/src/scss/custom/_variables.scss:ro
      - ./fdp/assets:/usr/share/nginx/html/assets:ro
      - ./fdp/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - fdp
    ports:
      - {FDP_PORT}:80  # You should/must close this port, if you are using hitch
    networks:
      - {PREFIX}-default


  graphdb:
    image: ontotext/graphdb:10.1.2
    restart: always
    hostname: graphdb
    ports:
      - {GDB_PORT}:7200
    volumes:
      - {PREFIX}-graphdb:/opt/graphdb/home
    networks:
      - {PREFIX}-default

  fdp:
    image: fairdata/fairdatapoint:1.16.2
    restart: always
    hostname: fdp
    volumes:
      - ./fdp/application-{PREFIX}.yml:/fdp/application.yml:ro
    depends_on:
      - mongo
      - graphdb
    networks:
      - {PREFIX}-default
        
  updater:
    image: markw/fdp-metadata-updater:0.0.3
    restart: always
    hostname: updater
    environment:
      DATA_SPARQL_ENDPOINT: ${DATA_SPARQL_ENDPOINT}
      DIST_RECORDID: ${DIST_RECORDID}
      DATASET_RECORDID: ${DATASET_RECORDID}
      DOMAIN: ${DOMAIN}
      FDP_USERNAME: ${FDP_USERNAME}
      FDP_PASSWORD: ${FDP_PASSWORD}
    networks:
      - {PREFIX}-default
      
  # Mongo for FDP server    
  mongo:
    image: mongo:4.2.3
    hostname: mongo
    restart: always
    volumes:
      - {PREFIX}-mongo-data:/data/db
      - {PREFIX}-mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - {PREFIX}-default

  cde-box-daemon: 
    image: markw/cde-box-daemon:0.5.2    # to use the CARE-SM models with teh care-sm-toolkit
    environment:
      GraphDB_User: ${GraphDB_User}
      GraphDB_Pass: ${GraphDB_Pass}
      baseURI: ${baseURI}
      GRAPHDB_REPONAME: ${GRAPHDB_REPONAME}
    depends_on:
      - caresm
      - yarrrml-rdfizer
    ports:
      - 127.0.0.1:{RDF_TRIGGER}:4567
    volumes:
      - ./data:/data
    networks:
      - {PREFIX}-default
                
  caresm:
    image: pabloalarconm/care-sm-toolkit:0.0.6
    hostname: caresm
    volumes:
      - ./data:/code/data
    networks:
      - {PREFIX}-default

  yarrrml-rdfizer:
    image: markw/yarrrml-rml-ejp:0.0.3
    hostname: yarrrml-rdfizer
    environment:
      # (nquads (default), trig, trix, jsonld, hdt, turtle)
      - SERIALIZATION=nquads
#    ports:
#      - "4567:4567"
    volumes:
      - ./data:/mnt/data
    networks:
      - {PREFIX}-default

  beacon_count:
    image: pabloalarconm/beacon-api4care-sm:0.1.0 
    hostname: beacon_count
    restart: always
    ports:
      - "{BEACON_PORT}:8000"
    environment:
      - TRIPLESTORE_URL=${DATA_SPARQL_ENDPOINT}
      - TRIPLESTORE_USERNAME=${GraphDB_User}
      - TRIPLESTORE_PASSWORD=${GraphDB_Pass}
      - FILTER_SEX=True
      - FILTER_DISEASE=True
      - FILTER_SYMPTOM=True
      - FILTER_GENE_VARIANT=True
      - FILTER_BIRTHYEAR=True
      - FILTER_AGE_SYMPTOM_ONSET=True
      - FILTER_AGE_DIAGNOSIS=True
      - URL_SERVER=http://my.server.org/beaconAPI/  # DO NOT include the path e.g. /individuals
    networks:
      - {PREFIX}-default


volumes:
  {PREFIX}-graphdb:
    external: true
  {PREFIX}-mongo-data:
    external: true
  {PREFIX}-mongo-init:
    external: true
  {PREFIX}-fdp-server:
    external: true

networks:
  {PREFIX}-default:
