#+ summary: Returns the number of patients in the registry with the corresponding disease code
#+ tags:
#+   - Patient Count
#+ defaults:
#+   - type: http://www.orpha.net/ORDO/Orphanet_98896
#+ endpoint_in_url: False

PREFIX sio: <http://semanticscience.org/resource/>
select (COUNT(?p) as ?count) where { 
    ?p sio:SIO_000008 ?a .
	?a a ?_type_iri .
}
