#+ summary: Returns the number of patients in the registry that have had a phenotype code at any time
#+ tags:
#+ - Phenotype frequency
#+ defaults:
#+ 
#+ endpoint_in_url: False

select ?type (count(?type) as ?frequency) where {
select distinct ?id ?type where {
?id a sio:SIO_000115 .
?id sio:SIO_000020 ?role .
?role sio:SIO_000356 ?process .
?process sio:SIO_000229 ?output . # has output
?output sio:SIO_000628 ?attribute . # refers to
?person sio:SIO_000008 ?attribute . # has-attribute
?attribute a sio:SIO_010056 .
?attribute a ?type .
?process sio:SIO_000229 ?output . # has output
?output sio:SIO_000628 ?attribute . # refers to
#?process sio:SIO_000680 ?timenode . # has start time
#?timenode sio:SIO_000300 ?date . # has value
FILTER(!(?type = sio:SIO_010056)) .
FILTER(!(?type = sio:SIO_000614)) .
}
} group by ?type
