
###############################################################
################## Required CSV column's names: ################

# pid: person identifier
# uniqid: unique identifier
# biobank_title: biobank name label

################################################################


prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  this: http://marks.test/this/
  dc: http://purl.org/dc/elements/1.1/

sources:
  cde_source: # cde_source: ["source_1.csv~csv"] For YARRRML Matey
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"

mappings:
  
  person_has_role:
    sources:
    - cde_source
    s: this:individual_$(pid)#Person
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    
    - predicates: sio:SIO_000228
      objects:
        value: this:individual_$(pid)_$(uniqid)#personRole
        type: iri
  
  person_has_role_sample_collection_process:
    sources:
    - cde_source
    s: this:individual_$(pid)_$(uniqid)#personRole
    po:
    - predicates: a
      objects:
        value: obo:OBI_0000093
        type: iri
    
    - predicates: sio:SIO_000356
      objects:
        value: this:individual_$(pid)_$(uniqid)#sampleCollectionProcess
        type: iri

  sample_collection_process_output:
    sources:
    - cde_source
    s: this:individual_$(pid)_$(uniqid)#sampleCollectionProcess
    po:
    - predicates: a
      objects:
        value: obo:OBI_0000659
        type: iri
    
    - predicates: sio:SIO_000229
      objects:
        value: this:individual_$(pid)_$(uniqid)#specimen
        type: iri

  output_specimen:
    sources:
    - cde_source
    s: this:individual_$(pid)_$(uniqid)#specimen
    po:
    - predicates: a
      objects:
        value: obo:OBI_0100051 
        type: iri

  biobank_has_role:
    sources:
    - cde_source
    s: this:individual_$(pid)#Biobank
    po:
    - predicates: a
      objects:
        value: obo:OMIABIS_0000010
        type: iri
    
    - predicates: dc:title
      objects:
        value: $(biobank_title)
        datatype: xsd:string

    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_$(pid)_$(uniqid)#biobankRole
        type: iri
  
  biobank_has_role_sample_storing_process:
    sources:
    - cde_source
    s: this:individual_$(pid)_$(uniqid)#biobankRole
    po:
    - predicates: a
      objects:
        value: obo:OBI_0000947
        type: iri
    
    - predicates: sio:SIO_000356
      objects:
        value: this:individual_$(pid)_$(uniqid)#sampleStoringProcess
        type: iri

  sample_storing_process_output:
    sources:
    - cde_source
    s: this:individual_$(pid)_$(uniqid)#sampleStoringProcess
    po:
    - predicates: a
      objects:
        value: obo:OBI_0302893
        type: iri
    
    - predicates: sio:SIO_000230
      objects:
        value: this:individual_$(pid)_$(uniqid)#specimen
        type: iri
