---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  patient_in_clinical_trial-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_thisPerson_person_clinical_trial_role:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_person_clinical_trial_role:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#person_clinical_trial_role
        type: iri
  entity_has_role_person_clinical_trial_role:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/object
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#person_clinical_trial_role
        type: iri
  person_clinical_trial_role_annotation:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#person_clinical_trial_role
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: " Role: Patient in clinical trial"
        datatype: xsd:string
  identifier_has_value_for_thisEntity_compound_clinical_trial_role:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisEntity_$(drugID)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(drugID)"
        datatype: xsd:string
  identifier_denotes_role_compound_clinical_trial_role:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisEntity_$(drugID)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_thisEntity_$(drugID)_$(uniqid)#compound_clinical_trial_role
        type: iri
  entity_has_role_compound_clinical_trial_role:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisEntity_$(drugID)#Entity
    po:
    - predicates: a
      objects:
        value: "$(drugURI)"
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/object
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_thisEntity_$(drugID)_$(uniqid)#compound_clinical_trial_role
        type: iri
  compound_clinical_trial_role_annotation:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisEntity_$(drugID)_$(uniqid)#compound_clinical_trial_role
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/SIO_010430
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: " Role: Compound tested in clinical trial"
        datatype: xsd:string
  compound_clinical_trial_role_entity_label_annotation:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_thisEntity_$(drugID)#Entity
    po:
    - predicates: rdfs:label
      objects:
        value: " Role: $(drugName)"
        datatype: xsd:string
  person_clinical_trial_role_realized_clinical_trial_process:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_$(pid)_$(uniqid)#person_clinical_trial_role
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_process#process_clinical_trial_process
        type: iri
  process_clinical_trial_process_process_annotation:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_$(pid)_process#process_clinical_trial_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C71104
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process: A clinical trial'
        datatype: xsd:string
  compound_clinical_trial_role_realized_clinical_trial_process:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_$(pid)_$(uniqid)#compound_clinical_trial_role
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_process#process_clinical_trial_process
        type: iri
  process_thisprocess_has_target_thisdisease:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_$(pid)_$(uniqid)_process#process_thisprocess
    po:
    - predicates: http://semanticscience.org/resource/has-target
      objects:
        value: this:individual_$(pid)_$(uniqid)#process_thisprocess_Target
        type: iri
  process_thisprocess_has_target_thisdisease_annotation:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_$(pid)_$(uniqid)#process_thisprocess_Target
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(diseaseURI)"
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process Target: $(diseaseLabel)'
        datatype: xsd:string
  process_has_agent_somedrug:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_$(pid)_$(uniqid)_process#clinical_trial_process
    po:
    - predicates: http://semanticscience.org/resource/has-agent
      objects:
        value: this:individual_somedrug_$(drugURI)#Entity
        type: iri
  parent_entity_has_part_somedrugcomponent1:
    sources:
    - patient_in_clinical_trial-source
    s: this:individual_somedrugcomponent1#comopnentEntity
    po:
    - predicates: rdf:type
      objects:
        value: "$(compoundURI)"
        type: iri
