---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_status-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_thisPerson_patientRole_status:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_status:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#patientRole_status
        type: iri
  entity_has_role_patientRole_status:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/object
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#patientRole_status
        type: iri
  patientRole_status_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#patientRole_status
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: " Role: Patient for status recording"
        datatype: xsd:string
  patientRole_status_realized_patient_status:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_status
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patient_status
        type: iri
  process_patient_status_process_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patient_status
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001052
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process: status recording process'
        datatype: xsd:string
  patientRole_status_realized_patient_death_information:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_status
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patient_death_information
        type: iri
  process_patient_death_information_process_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patient_death_information
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_001052
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process: death information recording process'
        datatype: xsd:string
  process_longitudinal_information_gathering_process_diseaseX_has_part_patient_status:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_process#process_longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: http://semanticscience.org/resource/has-part
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patient_status
        type: iri
  process_patient_status_process_has_type:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_process#process_patient_status
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
  process_patient_status_process_has_output:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patient_status
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#process_patient_status_Output
        type: iri
  process_patient_status_Output_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_status_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  process_patient_status_Output_type_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_status_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  process_patient_status_Output_type_label_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_status_Output
    po:
    - predicates: rdfs:label
      objects:
        value: 'Output Type: $(status_label)'
        datatype: xsd:string
  process_patient_status_Output_value_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_status_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(status_label)"
        datatype: xsd:string
  inout_from_process_patient_status_refers_to_concepts:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_patient_status_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#status_attribute_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_process_patient_status:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#status_attribute_TypedAttributeNode
        type: iri
  inout_from_process_patient_status_refers_to_concept_status_attribute_type:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#status_attribute_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(status_uri)"
        type: iri
  inout_from_process_patient_status_refers_to_concept_status_attribute_label:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#status_attribute_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: 'Attribute Type: Patient status'
        datatype: xsd:string
  process_patient_death_information_process_has_output:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patient_death_information
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#process_patient_death_information_Output
        type: iri
  process_patient_death_information_Output_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_death_information_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  process_patient_death_information_Output_type_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_death_information_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  process_patient_death_information_Output_type_label_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_death_information_Output
    po:
    - predicates: rdfs:label
      objects:
        value: 'Output Type: patient death information'
        datatype: xsd:string
  process_patient_death_information_Output_value_annotation:
    sources:
    - cde_patient_status-source
    s: this:individual_$(pid)_$(uniqid)#process_patient_death_information_Output
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(death_date)"
        datatype: xsd:date
  inout_from_process_patient_death_information_refers_to_concepts:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_patient_death_information_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#death_information_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_process_patient_death_information:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#death_information_TypedAttributeNode
        type: iri
  inout_from_process_patient_death_information_refers_to_concept_death_information_type:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#death_information_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C70810
        type: iri
  inout_from_process_patient_death_information_refers_to_concept_death_information_label:
    sources:
    - cde_patient_status-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#death_information_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: 'Attribute Type: Date of death'
        datatype: xsd:string
