---
prefixes:
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  ex: https://ejp-rd.eu/ids/
  obo: http://purl.obolibrary.org/obo/
  sio: http://semanticscience.org/resource/
  vocab: https://ejp-rd.eu/vocab/
  pico: https://data.cochrane.org/ontologies/pico/
  ndfrt: http://purl.bioontology.org/ontology/NDFRT/
  edam: http://purl.bioontology.org/ontology/EDAM/
  ordo: http://www.orpha.net/ORDO/
  this: "|||BASE|||"
sources:
  cde_patient_phenotyping-source:
    access: "|||DATA|||"
    referenceFormulation: "|||FORMULATION|||"
    iterator: "$"
mappings:
  identifier_has_value_for_thisPerson_patientRole_phenotyping:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(pid)"
        datatype: xsd:string
  identifier_denotes_role_patientRole_phenotyping:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)#ID
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/identifier
        type: iri
    - predicates: http://semanticscience.org/resource/denotes
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#patientRole_phenotyping
        type: iri
  entity_has_role_patientRole_phenotyping:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/person
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/object
        type: iri
    - predicates: http://semanticscience.org/resource/has-role
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#patientRole_phenotyping
        type: iri
  patientRole_phenotyping_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#patientRole_phenotyping
    po:
    - predicates: a
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0000093
        type: iri
    - predicates: a
      objects:
        value: http://semanticscience.org/resource/role
        type: iri
    - predicates: rdfs:label
      objects:
        value: " Role: Phenotyping Patient"
        datatype: xsd:string
  patientRole_phenotyping_realized_patientRole_phenotyping_process:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)#patientRole_phenotyping
    po:
    - predicates: http://semanticscience.org/resource/is-realized-in
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
        type: iri
  process_patientRole_phenotyping_process_process_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/OBI_0001546
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Process: comparative phenotypic assessment'
        datatype: xsd:string
  process_patientRole_phenotyping_process_process_annotation_start:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: http://semanticscience.org/resource/has-start-time
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process_startdate_$(date)
        type: iri
  process_patientRole_phenotyping_process_process_annotation_start_value:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process_startdate_$(date)
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/start-date
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'Start Date: $(date)'
        datatype: xsd:string
  process_patientRole_phenotyping_process_process_annotation_end:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: http://semanticscience.org/resource/has-end-time
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process_enddate_$(date)
        type: iri
  process_patientRole_phenotyping_process_process_annotation_end_value:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process_enddate_$(date)
    po:
    - predicates: http://semanticscience.org/resource/has-value
      objects:
        value: "$(date)"
        datatype: xsd:date
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/end-date
        type: iri
    - predicates: rdfs:label
      objects:
        value: 'End Date: $(date)'
        datatype: xsd:string
  16382584953291514_process_custom_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C16205
        type: iri
  16382584953291667_process_custom_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C18020
        type: iri
  process_longitudinal_information_gathering_process_diseaseX_has_part_patientRole_phenotyping_process:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_process#process_longitudinal_information_gathering_process_diseaseX
    po:
    - predicates: http://semanticscience.org/resource/has-part
      objects:
        value: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
        type: iri
  process_patientRole_phenotyping_process_process_has_type:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/process
        type: iri
  process_patientRole_phenotyping_process_process_has_output:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)_process#process_patientRole_phenotyping_process
    po:
    - predicates: http://semanticscience.org/resource/has-output
      objects:
        value: this:individual_$(pid)_$(uniqid)#process_patientRole_phenotyping_process_Output
        type: iri
  process_patientRole_phenotyping_process_Output_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)#process_patientRole_phenotyping_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/information-content-entity
        type: iri
  process_patientRole_phenotyping_process_Output_type_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)#process_patientRole_phenotyping_process_Output
    po:
    - predicates: rdf:type
      objects:
        value: http://purl.obolibrary.org/obo/NCIT_C102741
        type: iri
  process_patientRole_phenotyping_process_Output_type_label_annotation:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_$(pid)_$(uniqid)#process_patientRole_phenotyping_process_Output
    po:
    - predicates: rdfs:label
      objects:
        value: 'Output Type: $(HP_Label)'
        datatype: xsd:string
  inout_from_process_patientRole_phenotyping_process_refers_to_concepts:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#process_patientRole_phenotyping_process_Output
    po:
    - predicates: http://semanticscience.org/resource/refers-to
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#phenotyping_attribute_TypedAttributeNode
        type: iri
  has_attribute_of_inout_from_process_patientRole_phenotyping_process:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)#Entity
    po:
    - predicates: http://semanticscience.org/resource/has-attribute
      objects:
        value: this:individual_thisPerson_$(pid)_$(uniqid)#phenotyping_attribute_TypedAttributeNode
        type: iri
  inout_from_process_patientRole_phenotyping_process_refers_to_concept_phenotyping_attribute_type:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#phenotyping_attribute_TypedAttributeNode
    po:
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/attribute
        type: iri
    - predicates: rdf:type
      objects:
        value: "$(HP_IRI)"
        type: iri
    - predicates: rdf:type
      objects:
        value: http://semanticscience.org/resource/SIO_010056
        type: iri
  inout_from_process_patientRole_phenotyping_process_refers_to_concept_phenotyping_attribute_label:
    sources:
    - cde_patient_phenotyping-source
    s: this:individual_thisPerson_$(pid)_$(uniqid)#phenotyping_attribute_TypedAttributeNode
    po:
    - predicates: rdfs:label
      objects:
        value: 'Attribute Type: $(HP_Label)'
        datatype: xsd:string
